#!/usr/bin/env python3
"""Generate docs/INDEX.md: the single map of every report under docs/.

Status and grouping live here, not in the reports -- several reports are
overwritten in place by their generators, so any banner edited into them is
erased on the next run. This script owns that metadata and exits 1 when a
docs/*.md file is unclassified, so a new report can never silently escape the
index.

Run: .venv/bin/python scripts/build_docs_index.py
"""
from __future__ import annotations

import sys
from pathlib import Path

DOCS_DIR = Path(__file__).resolve().parents[1] / "docs"

# group -> rows of (filename_relative_to_docs, status, note, regen_cmd | None)
# status: current | generated | superseded | historical | stale
INDEX: dict[str, list[tuple[str, str, str, str | None]]] = {
    "Evaluation": [
        ("eval_report_expanded.md", "current",
         "32-task three-run router-vs-baseline eval; the live baseline.",
         ".venv/bin/python -m gatoway.eval --suite expanded"),
        ("eval_report.md", "current",
         "Legacy 16-task suite; still the default --suite legacy output.",
         ".venv/bin/python -m gatoway.eval"),
        ("evaluation_breadth.md", "current",
         "What the expanded 32-task suite covers and why it is a new baseline.",
         None),
        ("agentic_eval_report.md", "generated",
         "Agentic multi-step task eval.",
         ".venv/bin/python -m gatoway.agentic_eval"),
    ],
    "Routing policy": [
        ("policy_results.md", "current",
         "Seven-policy screening, 342/342 outcomes scored.",
         ".venv/bin/python scripts/report_policy_eval.py "
         "artifacts/policy_eval_20261004 --output docs/policy_results.md"),
        ("policy_comparison.md", "current",
         "Protocol and limitations for policy_results.md (hand-written).",
         None),
        ("downgrade_probe_results.md", "current",
         "Fresh-task validation of the strict_evidence downgrades; "
         "fence-normalization re-grading (hand-written verdict).", None),
        ("policy_results_probe.md", "generated",
         "Raw probe-run output (raw + fence-normalized columns); "
         "interpreted in downgrade_probe_results.md.",
         ".venv/bin/python scripts/report_policy_eval.py "
         "artifacts/policy_eval_probe_20261005 --output docs/policy_results_probe.md"),
    ],
    "Cost": [
        ("openrouter_cost_comparison.md", "current",
         "OpenRouter USD counterfactual: 25.5% on 54/96 matched pairs. "
         "Hand-written prose around reprice_eval.py JSON; no renderer.",
         None),
    ],
    "Training bank": [
        ("bootstrap_report.md", "current",
         "288-observation measured bank bootstrap.", None),
        ("bank_density.md", "generated", "Bank coverage/density report.",
         ".venv/bin/python -m gatoway.bank_density"),
        ("nrp_characterization.md", "current",
         "Measured NRP model inventory.",
         ".venv/bin/python -m gatoway.characterize"),
    ],
    "Judge": [
        ("judge_calibration.md", "current",
         "Live rubric-json-v2 calibration (hand-written).", None),
        ("judge_reliability.md", "current",
         "rubric-json-v2 reliability probe.", None),
    ],
    "Roadmap & specs": [
        ("tasks.md", "historical",
         "Original July MVP breakdown. Live roadmap is docs/plans/.", None),
        ("spec.md", "current", "Architecture spec (v0.2, NRP).", None),
        ("agentic_benchmarks.md", "current",
         "Agentic benchmark task definitions.", None),
    ],
    "Archive": [
        ("archive/judge_calibration_v1.md", "superseded",
         "Original prompt-only judge calibration; see judge_calibration.md.",
         None),
        ("archive/eval_report_pre_coding.md", "historical",
         "Eval snapshot before coding tasks were added.", None),
    ],
}


def classified() -> set[str]:
    return {row[0] for rows in INDEX.values() for row in rows}


def present() -> set[str]:
    top = {p.name for p in DOCS_DIR.glob("*.md") if p.name != "INDEX.md"}
    arch = {f"archive/{p.name}" for p in (DOCS_DIR / "archive").glob("*.md")}
    return top | arch


def unclassified() -> set[str]:
    return present() - classified()


def render() -> str:
    lines = [
        "# Docs index", "",
        "Generated by `scripts/build_docs_index.py` -- do not edit by hand.",
        "Status and grouping live here because several reports are overwritten "
        "in place by their generators.", "",
        "Status: **current** | **generated** (regenerable, see command) | "
        "**superseded** | **historical** | **stale**.", "",
    ]
    for group, rows in INDEX.items():
        lines += [f"## {group}", "", "| Report | Status | Notes |",
                  "|---|---|---|"]
        for name, status, note, _ in rows:
            lines.append(f"| [{name}]({name}) | {status} | {note} |")
        lines.append("")
    regen = [(n, c) for rows in INDEX.values() for n, _, _, c in rows if c]
    lines += [
        "## Regeneration", "",
        "Derived reports and the exact command that rewrites each. "
        "Regenerating needs the live eval run or a local `artifacts/` "
        "checkpoint; it is not cheap. Note: regenerating "
        "`eval_report_expanded.md` overwrites its hand-added monetary banner.",
        "", "| Report | Command |", "|---|---|",
    ]
    for name, cmd in regen:
        lines.append(f"| {name} | `{cmd}` |")
    lines += [
        "", "## Roadmap", "",
        "The live roadmap is the dated plans in [docs/plans/](plans/) and the "
        "specs in [docs/specs/](specs/).", "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    missing = unclassified()
    if missing:
        print("Unclassified docs (add to INDEX in build_docs_index.py):",
              file=sys.stderr)
        for name in sorted(missing):
            print(f"  {name}", file=sys.stderr)
        return 1
    (DOCS_DIR / "INDEX.md").write_text(render())
    print(f"Wrote {DOCS_DIR / 'INDEX.md'} ({len(classified())} reports)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
